name: Markdown lint

on:
  push:
    branches: [ main ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: 'restqa-404-links'
      uses: restqa/404-links@2dddde704a1633e9a55ad78d36a0149de9c89d5a # 3.1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
